version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eshop
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ~/Desktop/ELK/postgres_container_data:/var/lib/postgresql/data
    networks:
      - aryak-network

  eshop-app:
    image: aryak0512/eshop:latest
    container_name: eshop
    environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/eshop
      #SPRING_DATASOURCE_USERNAME: ENC(4+jyV/8QVvIOUGsFyWHA4yaYPL1iZibXgXHdvUSo4MbZDqTomubI83x0wtiaUCwr)
      #SPRING_DATASOURCE_PASSWORD: ENC(5dpaJhc5Hb/9eQ/T9dYek/5fm8WyNzWdeQ7M2j62Lk0PBwbNkFrkQLwEJffGzVRb)
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8900:8900"
    networks:
      - aryak-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=aryak
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ~/Desktop/ELK/elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - aryak-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
    volumes:
      - aryak-volume:/usr/share/kibana/data
    networks:
      - aryak-network

volumes:
  aryak-volume:

networks:
  aryak-network:
