version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eshop
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aryak-network

  eshop-app:
    image: aryak0512/eshop:latest
    container_name: eshop
    environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/eshop
      #SPRING_DATASOURCE_USERNAME: ENC(4+jyV/8QVvIOUGsFyWHA4yaYPL1iZibXgXHdvUSo4MbZDqTomubI83x0wtiaUCwr)
      #SPRING_DATASOURCE_PASSWORD: ENC(5dpaJhc5Hb/9eQ/T9dYek/5fm8WyNzWdeQ7M2j62Lk0PBwbNkFrkQLwEJffGzVRb)
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8900:8900"
    networks:
      - aryak-network

networks:
  aryak-network:
